title: "AthenaPro"
description: "Site de portfolios professionnels"
baseurl: ""
url: "https://athenapro.ovh"
theme: minima

plugins:
  - jekyll-multiple-languages-plugin

languages: ["fr", "en"]
default_lang: "fr"
