name: Génération Quotidienne Blog AthenaPro

on:
  schedule:
    - cron: '0 7 * * *'  # 07:00 UTC = 09:00 Paris
  workflow_dispatch:

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4
        with:
          ref: gh-page
          fetch-depth: 0

      - name: Configuration Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installation dépendances Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Installation GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Configuration GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: Installation Copilot CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install github/gh-copilot
          gh copilot --version

      - name: Test Copilot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Test Copilot connection" | gh copilot suggest || true
          
      - name: Génération Article
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/generate_blog_post.py

      - name: Commit & Push
        run: |
          git add _posts/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "📝 Nouvel article généré par Copilot"
            git push origin gh-page
            echo "✅ Article publié avec succès"
          else
            echo "ℹ️ Aucun nouvel article à publier"
          fi
